function hdpoin
    %hdpoin
    %this subroutine interpolates back to the particles positions.
    
    %======================================================
	%Llamado de variables globales
    global ghsubxG ghsubyG wtsG n idsG ghxpG ghypG
    %======================================================
    disp('HDPOIN....................');
      for in=1:n;
         
         ii= idsG(in,1);
         jj= idsG(in,2);
         
%          ghxp(in)= wtsG(in,1,1)*ghsubxG(ii-1,jj-1)+wtsG(in,2,1)*ghsubxG(ii,jj-1)+wtsG(in,3,1)*ghsubxG(ii+1,jj-1)+wtsG(in,1,2)*ghsubxG(ii-1,jj)+wtsG(in,2,2)*ghsubxG(ii,jj)+wtsG(in,3,2)*ghsubxG(ii+1,jj)+wtsG(in,1,3)*ghsubxG(ii-1,jj+1)+wtsG(in,2,3)*ghsubxG(ii,jj+1)+wtsG(in,3,3)*ghsubxG(ii+1,jj+1);
%          
%          ghyp(in)= wtsG(in,1,1)*ghsubyG(ii-1,jj-1)+wtsG(in,2,1)*ghsubyG(ii,jj-1)+wtsG(in,3,1)*ghsubyG(ii+1,jj-1)+wtsG(in,1,2)*ghsubyG(ii-1,jj)+wtsG(in,2,2)*ghsubyG(ii,jj)+wtsG(in,3,2)*ghsubyG(ii+1,jj)+wtsG(in,1,3)*ghsubyG(ii-1,jj+1)+wtsG(in,2,3)*ghsubyG(ii,jj+1)+wtsG(in,3,3)*ghsubyG(ii+1,jj+1);

         ghxpG(in)= wtsG(in,1,1)*ghsubxG(jj-1,ii-1)+...
             wtsG(in,1,2)*ghsubxG(jj,ii-1)+...
             wtsG(in,1,3)*ghsubxG(jj+1,ii-1)+...
             wtsG(in,2,1)*ghsubxG(jj-1,ii)+...
             wtsG(in,2,2)*ghsubxG(jj,ii)+...
             wtsG(in,2,3)*ghsubxG(jj+1,ii)+...
             wtsG(in,3,1)*ghsubxG(jj-1,ii+1)+...
             wtsG(in,3,2)*ghsubxG(jj,ii+1)+...
             wtsG(in,3,3)*ghsubxG(jj+1,ii+1);
         
         ghypG(in)= wtsG(in,1,1)*ghsubyG(jj-1,ii-1)+...
             wtsG(in,1,2)*ghsubyG(jj,ii-1)+...
             wtsG(in,1,3)*ghsubyG(jj+1,ii-1)+...
             wtsG(in,2,1)*ghsubyG(jj-1,ii)+...
             wtsG(in,2,2)*ghsubyG(jj,ii)+...
             wtsG(in,2,3)*ghsubyG(jj+1,ii)+...
             wtsG(in,3,1)*ghsubyG(jj-1,ii+1)+...
             wtsG(in,3,2)*ghsubyG(jj,ii+1)+...
             wtsG(in,3,3)*ghsubyG(jj+1,ii+1); 
         
      end    
    
end